# Generated by Django 2.0.7 on 2018-07-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='slides',
            field=models.ManyToManyField(to='project.Slide'),
        ),
    ]
