# Generated by Django 2.0.7 on 2018-07-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='project_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
