# Generated by Django 2.0.7 on 2018-07-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_slide_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slides',
            field=models.ManyToManyField(blank=True, to='project.Slide'),
        ),
    ]
