# Generated by Django 2.0.7 on 2018-07-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180718_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='image_url',
        ),
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
