# Generated by Django 2.0.7 on 2018-08-06 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20180720_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slides',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='project_name',
        ),
        migrations.AddField(
            model_name='slide',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='project.Project'),
        ),
    ]
